<?php

/**
 * @var \Amasty\CyxapkoModule\Block\Index $block
 */



?>
<form id="my-form" method="post">
    <div>
        <label for="sku">sku:</label>
        <input type="text" name="sku" />
    </div>
    <?php if ($block->isQtyHidden()): ?>
        <div>
            <label for="qty">qty:</label>
            <input type="number" name="qty" value="<?= $block->getViewQtyValue() ?>" />
        </div>
    <?php endif; ?>
    <?php echo $block->getChildHtml('Amasty_CyxapkoModule.additional') ?>
    <div>
        <button type="submit">button</button>
    </div>
</form>